/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CalculatorDemo;
import java.awt.Toolkit;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import java.util.Scanner;
/**
 *
 * @author NANU
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    double first=0,second=0,result=0;
    char opr;
    Scanner sc=new Scanner(System.in);
    public Calculator() {
        initComponents();
        setIcon();
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Display = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        bmul = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bequal = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bsub = new javax.swing.JButton();
        badd = new javax.swing.JButton();
        Display0 = new javax.swing.JTextField();
        bsign = new javax.swing.JButton();
        bback = new javax.swing.JButton();
        bsqrt = new javax.swing.JButton();
        bdot = new javax.swing.JButton();
        bcbrt = new javax.swing.JButton();
        bbacksp = new javax.swing.JButton();
        bpow = new javax.swing.JButton();
        bfact = new javax.swing.JButton();
        brpcl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Calculator");
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "CALCULATOR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Comic Sans MS", 1, 24), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        Display.setEditable(false);
        Display.setBackground(new java.awt.Color(0, 204, 204));
        Display.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Display.setForeground(new java.awt.Color(255, 255, 255));
        Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });

        b1.setBackground(java.awt.Color.lightGray);
        b1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(java.awt.Color.lightGray);
        b2.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b4.setBackground(java.awt.Color.lightGray);
        b4.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setBackground(java.awt.Color.lightGray);
        b5.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b7.setBackground(java.awt.Color.lightGray);
        b7.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setBackground(java.awt.Color.lightGray);
        b8.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b0.setBackground(java.awt.Color.lightGray);
        b0.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        bclear.setBackground(java.awt.Color.orange);
        bclear.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        bclear.setText("C");
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });

        b3.setBackground(java.awt.Color.lightGray);
        b3.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        bdiv.setBackground(java.awt.Color.orange);
        bdiv.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        bdiv.setText("/");
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });

        bmul.setBackground(java.awt.Color.orange);
        bmul.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        bmul.setText("*");
        bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulActionPerformed(evt);
            }
        });

        b9.setBackground(java.awt.Color.lightGray);
        b9.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        bequal.setBackground(java.awt.Color.lightGray);
        bequal.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        bequal.setText("=");
        bequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bequalActionPerformed(evt);
            }
        });

        b6.setBackground(java.awt.Color.lightGray);
        b6.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        bsub.setBackground(java.awt.Color.orange);
        bsub.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        bsub.setText("-");
        bsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubActionPerformed(evt);
            }
        });

        badd.setBackground(java.awt.Color.orange);
        badd.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        badd.setText("+");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });

        Display0.setEditable(false);
        Display0.setBackground(new java.awt.Color(0, 204, 204));
        Display0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bsign.setBackground(java.awt.Color.orange);
        bsign.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        bsign.setText("+/-");
        bsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsignActionPerformed(evt);
            }
        });

        bback.setBackground(java.awt.Color.orange);
        bback.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        bback.setText("CE");
        bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbackActionPerformed(evt);
            }
        });

        bsqrt.setBackground(java.awt.Color.orange);
        bsqrt.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        bsqrt.setText("sqrt");
        bsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsqrtActionPerformed(evt);
            }
        });

        bdot.setBackground(java.awt.Color.lightGray);
        bdot.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        bdot.setText(".");
        bdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdotActionPerformed(evt);
            }
        });

        bcbrt.setBackground(java.awt.Color.orange);
        bcbrt.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        bcbrt.setText("cbrt");
        bcbrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcbrtActionPerformed(evt);
            }
        });

        bbacksp.setBackground(java.awt.Color.orange);
        bbacksp.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 12)); // NOI18N
        bbacksp.setText("back");
        bbacksp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbackspActionPerformed(evt);
            }
        });

        bpow.setBackground(java.awt.Color.orange);
        bpow.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        bpow.setText("pow");
        bpow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpowActionPerformed(evt);
            }
        });

        bfact.setBackground(java.awt.Color.orange);
        bfact.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        bfact.setText("n!");
        bfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfactActionPerformed(evt);
            }
        });

        brpcl.setBackground(java.awt.Color.orange);
        brpcl.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        brpcl.setText("1/x");
        brpcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brpclActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Display0)
            .addComponent(Display)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsub, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bback, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bsign, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bfact, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bpow, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bbacksp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bcbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bdot, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(bequal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brpcl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {b0, b7, b8, b9, badd, bback, bbacksp, bclear, bdot, bfact, bmul, bsign, bsub});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {b1, b2, b3, bdiv, bsqrt});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bequal, brpcl});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Display0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bsign, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bback, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bfact, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bsub, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bequal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bdot, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bbacksp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(bcbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bpow, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brpcl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {b0, b1, b2, b3, b7, b8, b9, badd, bback, bbacksp, bclear, bdiv, bdot, bequal, bfact, bmul, brpcl, bsign, bsqrt, bsub});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        if(Display.getText().contentEquals("0"))
            Display.setText("");
        if(opr=='='){
           Display.setText("");
           Display0.setText("");
           opr='0';
        }
        String s=Display.getText()+b5.getText();
        Display.setText(s);
    }//GEN-LAST:event_b5ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        if(Display.getText().contentEquals("0"))
            Display.setText("");
        if(opr=='='){
           Display.setText("");
           Display0.setText("");
           opr='0';
        }
       String s=Display.getText()+b7.getText();
        Display.setText(s);
    }//GEN-LAST:event_b7ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        if(Display.getText().contentEquals("0"))
            Display.setText("");
        if(opr=='='){
           Display.setText("");
           Display0.setText("");
           opr='0';
        }
        String s=Display.getText()+b9.getText();
        Display.setText(s);
    }//GEN-LAST:event_b9ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if(Display.getText().contentEquals("0"))
            Display.setText("");
        if(opr=='='){
           Display.setText("");
           Display0.setText("");
           opr='0';
        }
       String s=Display.getText()+b1.getText();
        Display.setText(s);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if(Display.getText().contentEquals("0"))
            Display.setText("");
        if(opr=='='){
           Display.setText("");
           Display0.setText("");
           opr='0';
        }
        String s=Display.getText()+b2.getText();
        Display.setText(s);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        if(Display.getText().contentEquals("0"))
            Display.setText("");
        if(opr=='='){
           Display.setText("");
           Display0.setText("");
           opr='0';
        }
        String s=Display.getText()+b3.getText();
        Display.setText(s);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        if(Display.getText().contentEquals("0"))
            Display.setText("");
        if(opr=='='){
           Display.setText("");
           Display0.setText("");
           opr='0';
        }
        String s=Display.getText()+b4.getText();
        Display.setText(s);
    }//GEN-LAST:event_b4ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
       if(Display.getText().contentEquals("0"))
            Display.setText("");
       if(opr=='='){
           Display.setText("");
           Display0.setText("");
           opr='0';
        }
        String s=Display.getText()+b6.getText();
        Display.setText(s);
    }//GEN-LAST:event_b6ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        if(Display.getText().contentEquals("0"))
            Display.setText("");
        if(opr=='='){
           Display.setText("");
           Display0.setText("");
           opr='0';
        }
        String s=Display.getText()+b8.getText();
        Display.setText(s);
    }//GEN-LAST:event_b8ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        if(Display.getText().contentEquals("0"))
            Display.setText("");
        if(opr=='='){
           Display.setText("");
           Display0.setText("");
           opr='0';
        }
        String s=Display.getText()+b0.getText();
        Display.setText(s);
        if(Display0.getText().contentEquals("0"))
            Display0.setText("");
    }//GEN-LAST:event_b0ActionPerformed

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        // TODO add your handling code here:
         String s=Display.getText(),s1=Display0.getText(),x;
         if(!s1.isEmpty())
         {
             if(opr=='='){
           s1="";
           opr='0';
        }
            if(!s.isEmpty())
            {
                if(s.startsWith("-")){
                  x='('+s+')';
                  Display0.setText(s1+x+'+');
             }
             else
             Display0.setText(s1+s+'+');
            }
             
         }
         else{
             Display0.setText(s+'+');
         }
         checkOpr(s);
        opr='+';
         Display.setText("");
    }//GEN-LAST:event_baddActionPerformed

    private void bsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubActionPerformed
        // TODO add your handling code here:
        String s=Display.getText(),s1=Display0.getText(),x;
        if(!s1.isEmpty())
         {
             if(opr=='='){
           s1="";
           opr='0';
        }
              if(!s.isEmpty()){
             if(s.startsWith("-")){
                 x='('+s+')';
                Display0.setText(s1+x+'-');
             }
             else
                  Display0.setText(s1+s+'-');
         }
         }
         else{
             Display0.setText(s+'-');
         }
         checkOpr(s);
        opr='-';
         Display.setText("");
    }//GEN-LAST:event_bsubActionPerformed

    private void bmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulActionPerformed
        // TODO add your handling code here:
        String s=Display.getText(),s1=Display0.getText(),x;
        if(!s1.isEmpty())
         {
             if(opr=='='){
           s1="";
           opr='0';
        }
              if(!s.isEmpty()){
             if(s.startsWith("-")){
                 x='('+s+')';
        Display0.setText(s1+x+'*');
             }
            else
                 Display0.setText(s1+s+'*');
         }
         }
         else{
             Display0.setText(s+'*');
         }
         checkOpr(s);
        opr='*';
         Display.setText("");
    }//GEN-LAST:event_bmulActionPerformed

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
        // TODO add your handling code here:
        String s=Display.getText(),s1=Display0.getText(),x;
        if(!s1.isEmpty())
         {
             if(opr=='='){
           s1="";
           opr='0';
        }
              if(!s.isEmpty()){
             if(s.startsWith("-")){
                 x='('+s+')';
        Display0.setText(s1+x+'/');
             }
            else
                 Display0.setText(s1+s+'/');
         }
         }
         else{
             Display0.setText(s+'/');
         }
         checkOpr(s);
        opr='/';
         Display.setText("");
    }//GEN-LAST:event_bdivActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        // TODO add your handling code here:
       Display.setText("0");
        Display0.setText("");
       first=second=result=0;
    }//GEN-LAST:event_bclearActionPerformed

    private void bequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bequalActionPerformed
        // TODO add your handling code here:
        String s=Display.getText(),s1=Display0.getText();
        second=Double.parseDouble(s);
        if(opr=='+')
        {
            result=first+second;
            if(String.valueOf(result).endsWith(".0"))
            {
                long r=(long)result;
                Display.setText(String.valueOf(r));
                if(s.startsWith("-"))
                    s1=s1+'('+s+')'+'='+r;
                else
                    s1=s1+s+'='+r;
            Display0.setText(s1);
            }
            else{
                Display.setText(String.valueOf(result));
            if(s.startsWith("-"))
                    s1=s1+'('+s+')'+'='+result;
                else
                    s1=s1+s+'='+result;
            Display0.setText(s1);
           }    
        }
        if(opr=='-')
        {
            result=first-second;
            if(String.valueOf(result).endsWith(".0"))
            {
                long r=(long)result;
                Display.setText(String.valueOf(r));
            if(s.startsWith("-"))
                    s1=s1+'('+s+')'+'='+r;
                else
                    s1=s1+s+'='+r;
            Display0.setText(s1);
            }
            else{
                Display.setText(String.valueOf(result));
             if(s.startsWith("-"))
                    s1=s1+'('+s+')'+'='+result;
                else
                    s1=s1+s+'='+result;
            Display0.setText(s1);
           }    
        }
        if(opr=='*')
        {
            result=first*second;
            if(String.valueOf(result).endsWith(".0"))
            {
                long r=(long)result;
                Display.setText(String.valueOf(r));
             if(s.startsWith("-"))
                    s1=s1+'('+s+')'+'='+r;
                else
                    s1=s1+s+'='+r;
            Display0.setText(s1);
            }
            else{
                Display.setText(String.valueOf(result));
             if(s.startsWith("-"))
                    s1=s1+'('+s+')'+'='+result;
                else
                    s1=s1+s+'='+result;
            Display0.setText(s1);
           }    
        }
        if(opr=='/')
        {
            result=first/second;
            if(String.valueOf(result).endsWith(".0"))
            {
                long r=(long)result;
                Display.setText(String.valueOf(r));
             if(s.startsWith("-"))
                    s1=s1+'('+s+')'+'='+r;
                else
                    s1=s1+s+'='+r;
            Display0.setText(s1);
            }
            else{
                Display.setText(String.valueOf(result));
             if(s.startsWith("-"))
                    s1=s1+'('+s+')'+'='+result;
                else
                    s1=s1+s+'='+result;
            Display0.setText(s1);
           }    
        }
        if(opr=='p')
        {
            result=Math.pow(first, second);
            if(String.valueOf(result).endsWith(".0"))
            {
                long r=(long)result;
                Display.setText(String.valueOf(r));
                if(s.startsWith("-"))
                    s1=s1+'('+s+')'+'='+r;
                else
                    s1=s1+s+'='+r;
            Display0.setText(s1);
            }
            else{
                Display.setText(String.valueOf(result));
            if(s.startsWith("-"))
                    s1=s1+'('+s+')'+'='+result;
                else
                    s1=s1+s+'='+result;
            Display0.setText(s1);
           }    
        }
        first=second=result=0;
             opr='=';       
    }//GEN-LAST:event_bequalActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayActionPerformed

    private void bsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsignActionPerformed
        // TODO add your handling code here:
        String s=Display.getText(),s1=Display0.getText();
        if(!s.isEmpty()){
        Double d=Double.parseDouble(s);
        if(d!=0)
            d=-d;
        if(String.valueOf(d).contains(".0"))
             {
                    long r=(long) Math.round(d);
                    Display.setText(String.valueOf(r));
             }
        else
        Display.setText(String.valueOf(d)); 
        }
    }//GEN-LAST:event_bsignActionPerformed

    private void bbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbackActionPerformed
        // TODO add your handling code here:
        Display.setText("");
    }//GEN-LAST:event_bbackActionPerformed

    private void bsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsqrtActionPerformed
        String s=Display.getText();
        if(!s.isEmpty())
        {
            Double d=Math.sqrt(Double.parseDouble(s));
            if(String.valueOf(d).endsWith(".0"))
            {
                long r=(long) Math.round(d);
                Display.setText(String.valueOf(r));
                String s2="sqrt("+s+")="+r;
                Display0.setText(s2);
            }
            else{
                 String s2="sqrt("+s+")="+d;
                Display.setText(String.valueOf(d));
            Display0.setText(s2);
           } 
           opr='=';
        }
    }//GEN-LAST:event_bsqrtActionPerformed

    private void bdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdotActionPerformed
        // TODO add your handling code here:
        if(opr=='='){
           Display.setText("");
           Display0.setText("");
           opr='0';
        }
        String s=Display.getText(),s1=Display0.getText();
        if(s.isEmpty()||s.contentEquals("0")){
            s="0.";
            Display.setText(s);
        }
        else{
            if(!s.contains(".")){
                s=s+".";
             Display.setText(s);
            }
            
        }
    }//GEN-LAST:event_bdotActionPerformed

    private void bcbrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcbrtActionPerformed
         String s=Display.getText();
        if(!s.isEmpty())
        {
            Double d=Math.cbrt(Double.parseDouble(s));
            if(String.valueOf(d).endsWith(".0"))
            {
                long r=(long) Math.round(d);
                Display.setText(String.valueOf(r));
                String s2="cbrt("+s+")="+r;
                Display0.setText(s2);
            }
            else{
                 String s2="cbrt("+s+")="+d;
                Display.setText(String.valueOf(d));
            Display0.setText(s2);
           } 
           opr='=';
        }
    }//GEN-LAST:event_bcbrtActionPerformed

    private void bbackspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbackspActionPerformed
        // TODO add your handling code here:
        String s=Display.getText();
        if(!s.isEmpty()){
        s=s.substring(0,s.length()-1);
        Display.setText(s);
        }
    }//GEN-LAST:event_bbackspActionPerformed

    private void bpowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpowActionPerformed
         String s=Display.getText();
        if(!s.isEmpty())
        {
            first=Double.parseDouble(s);
            Display.setText("");
            Display0.setText(s+'^');
            opr='p';
        }
    }//GEN-LAST:event_bpowActionPerformed

    private void bfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfactActionPerformed
        // TODO add your handling code here:
        String s=Display.getText();
        if(!s.isEmpty())
        {
            Double d=Double.parseDouble(s),f=1.0;
            for(double i=d;i>=0;i--)
            {   
                if(i==0)
                    break;
                f*=i;
            }
            if(String.valueOf(f).endsWith(".0"))
            {
                long r=(long) Math.round(f);
                Display.setText(String.valueOf(r));
                String s2=s+"!="+r;
                Display0.setText(s2);
            }
            else{
                 String s2=s+"!="+f;
                Display.setText(String.valueOf(f));
            Display0.setText(s2);
           } 
           opr='=';
        }
    }//GEN-LAST:event_bfactActionPerformed

    private void brpclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brpclActionPerformed
        // TODO add your handling code here:
        String s=Display.getText();
        if(!s.isEmpty())
        {
            Double d=1/(Double.parseDouble(s));
            if(String.valueOf(d).endsWith(".0"))
            {
                long r=(long) Math.round(d);
                Display.setText(String.valueOf(r));
                String s2="reciprocal("+s+")="+r;
                Display0.setText(s2);
            }
            else{
                 String s2="reciprocal("+s+")="+d;
                Display.setText(String.valueOf(d));
            Display0.setText(s2);
           } 
           opr='=';
        }
    }//GEN-LAST:event_brpclActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (longroduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Display;
    private javax.swing.JTextField Display0;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton badd;
    private javax.swing.JButton bback;
    private javax.swing.JButton bbacksp;
    private javax.swing.JButton bcbrt;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bdot;
    private javax.swing.JButton bequal;
    private javax.swing.JButton bfact;
    private javax.swing.JButton bmul;
    private javax.swing.JButton bpow;
    private javax.swing.JButton brpcl;
    private javax.swing.JButton bsign;
    private javax.swing.JButton bsqrt;
    private javax.swing.JButton bsub;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
    private void checkOpr(String s){
        switch (opr) {
            case '+':
                first+=Double.parseDouble(s);
                break;
            case '-':
                first-=Double.parseDouble(s);
                break;
            case '*':
                first*=Double.parseDouble(s);
                break;
            case '/':
                first/=Double.parseDouble(s);
                break;
            default:
                first=Double.parseDouble(s);
                break;
        }
    }

  
}
